Launced with slurm
Launced with slurm
Launced with slurm
Launced with slurm
world size, rank, gpu, device count: 4 1 1 4
world size, rank, gpu, device count: 4 3 3 4
world size, rank, gpu, device count: 4 2 2 4
world size, rank, gpu, device count: 4 0 0 4
| distributed init (rank 0): env://
| distributed init (rank 1): env://
| distributed init (rank 2): env://
| distributed init (rank 3): env://
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
git:
  sha: N/A, status: clean, branch: N/A

arch: vit_large
batch_size_per_gpu: 52
clip_grad: 1.0
data_path: /scratch/eo41/data/saycam/SAY_5fps_300s_{000000..000009}.tar
dist_url: env://
epochs: 100
freeze_last_layer: 0
global_crops_scale: [0.2, 1.0]
gpu: 0
local_crops_number: 8
local_crops_scale: [0.05, 0.2]
local_rank: 0
lr: 0.0001
min_lr: 0.0001
momentum_teacher: 0.9995
norm_last_layer: True
num_workers: 8
optimizer: adamw
out_dim: 65536
output_dir: /scratch/eo41/dino/models_vitl
patch_size: 16
print_freq: 5000
rank: 0
save_prefix: say_5fps_vitl16
saveckp_freq: 5000
seed: 1
teacher_temp: 0.04
use_bn_in_head: False
use_fp16: False
warmup_epochs: 0
warmup_teacher_temp: 0.04
warmup_teacher_temp_epochs: 0
weight_decay: 0.0
weight_decay_end: 0.0
world_size: 4
/scratch/eo41/miniconda3/lib/python3.9/site-packages/torchvision/transforms/transforms.py:852: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  warnings.warn(
/scratch/eo41/miniconda3/lib/python3.9/site-packages/torch/utils/data/dataloader.py:478: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 4, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
Data loaded.
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
/scratch/eo41/miniconda3/lib/python3.9/site-packages/torchvision/transforms/transforms.py:852: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  warnings.warn(
/scratch/eo41/miniconda3/lib/python3.9/site-packages/torchvision/transforms/transforms.py:852: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  warnings.warn(
/scratch/eo41/miniconda3/lib/python3.9/site-packages/torchvision/transforms/transforms.py:852: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  warnings.warn(
/scratch/eo41/miniconda3/lib/python3.9/site-packages/torch/utils/data/dataloader.py:478: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 4, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
/scratch/eo41/miniconda3/lib/python3.9/site-packages/torch/utils/data/dataloader.py:478: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 4, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
/scratch/eo41/miniconda3/lib/python3.9/site-packages/torch/utils/data/dataloader.py:478: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 4, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
Student and Teacher are built: they are both vit_large network.
Loss, optimizer and schedulers ready.
Starting DINO training !
/scratch/eo41/miniconda3/lib/python3.9/site-packages/torch/nn/functional.py:3631: UserWarning: Default upsampling behavior when mode=bicubic is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  warnings.warn(
/scratch/eo41/miniconda3/lib/python3.9/site-packages/torch/nn/functional.py:3631: UserWarning: Default upsampling behavior when mode=bicubic is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  warnings.warn(
/scratch/eo41/miniconda3/lib/python3.9/site-packages/torch/nn/functional.py:3679: UserWarning: The default behavior for interpolate/upsample with float scale_factor changed in 1.6.0 to align with other frameworks/libraries, and now uses scale_factor directly, instead of relying on the computed output size. If you wish to restore the old behavior, please set recompute_scale_factor=True. See the documentation of nn.Upsample for details. 
  warnings.warn(
/scratch/eo41/miniconda3/lib/python3.9/site-packages/torch/nn/functional.py:3679: UserWarning: The default behavior for interpolate/upsample with float scale_factor changed in 1.6.0 to align with other frameworks/libraries, and now uses scale_factor directly, instead of relying on the computed output size. If you wish to restore the old behavior, please set recompute_scale_factor=True. See the documentation of nn.Upsample for details. 
  warnings.warn(
/scratch/eo41/miniconda3/lib/python3.9/site-packages/torch/nn/functional.py:3631: UserWarning: Default upsampling behavior when mode=bicubic is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  warnings.warn(
/scratch/eo41/miniconda3/lib/python3.9/site-packages/torch/nn/functional.py:3679: UserWarning: The default behavior for interpolate/upsample with float scale_factor changed in 1.6.0 to align with other frameworks/libraries, and now uses scale_factor directly, instead of relying on the computed output size. If you wish to restore the old behavior, please set recompute_scale_factor=True. See the documentation of nn.Upsample for details. 
  warnings.warn(
/scratch/eo41/miniconda3/lib/python3.9/site-packages/torch/nn/functional.py:3631: UserWarning: Default upsampling behavior when mode=bicubic is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  warnings.warn(
/scratch/eo41/miniconda3/lib/python3.9/site-packages/torch/nn/functional.py:3679: UserWarning: The default behavior for interpolate/upsample with float scale_factor changed in 1.6.0 to align with other frameworks/libraries, and now uses scale_factor directly, instead of relying on the computed output size. If you wish to restore the old behavior, please set recompute_scale_factor=True. See the documentation of nn.Upsample for details. 
  warnings.warn(
Averaged stats: loss: 10.731761 (10.739905)  lr: 0.000100 (0.000100)  wd: 0.000000 (0.000000)
Averaged stats: loss: 10.970417 (11.038328)  lr: 0.000100 (0.000100)  wd: 0.000000 (0.000000)
Averaged stats: loss: 10.629999 (10.790595)  lr: 0.000100 (0.000100)  wd: 0.000000 (0.000000)
Averaged stats: loss: 10.523779 (10.559745)  lr: 0.000100 (0.000100)  wd: 0.000000 (0.000000)
Averaged stats: loss: 10.186438 (10.336635)  lr: 0.000100 (0.000100)  wd: 0.000000 (0.000000)
Averaged stats: loss: 9.930804 (10.021043)  lr: 0.000100 (0.000100)  wd: 0.000000 (0.000000)
Averaged stats: loss: 9.561434 (9.635586)  lr: 0.000100 (0.000100)  wd: 0.000000 (0.000000)
Averaged stats: loss: 8.795742 (9.125656)  lr: 0.000100 (0.000100)  wd: 0.000000 (0.000000)
Averaged stats: loss: 7.861083 (8.371649)  lr: 0.000100 (0.000100)  wd: 0.000000 (0.000000)
Averaged stats: loss: 7.259861 (7.558713)  lr: 0.000100 (0.000100)  wd: 0.000000 (0.000000)
Averaged stats: loss: 6.574652 (6.893460)  lr: 0.000100 (0.000100)  wd: 0.000000 (0.000000)
Averaged stats: loss: 5.993560 (6.366268)  lr: 0.000100 (0.000100)  wd: 0.000000 (0.000000)
Averaged stats: loss: 5.613018 (5.940268)  lr: 0.000100 (0.000100)  wd: 0.000000 (0.000000)
Averaged stats: loss: 5.394228 (5.612862)  lr: 0.000100 (0.000100)  wd: 0.000000 (0.000000)
Averaged stats: loss: 5.375727 (5.353197)  lr: 0.000100 (0.000100)  wd: 0.000000 (0.000000)
Averaged stats: loss: 5.001420 (5.137650)  lr: 0.000100 (0.000100)  wd: 0.000000 (0.000000)
Averaged stats: loss: 4.906531 (4.984496)  lr: 0.000100 (0.000100)  wd: 0.000000 (0.000000)
Averaged stats: loss: 4.729547 (4.865213)  lr: 0.000100 (0.000100)  wd: 0.000000 (0.000000)
Averaged stats: loss: 4.617033 (4.773219)  lr: 0.000100 (0.000100)  wd: 0.000000 (0.000000)
Averaged stats: loss: 4.725472 (4.718563)  lr: 0.000100 (0.000100)  wd: 0.000000 (0.000000)
Traceback (most recent call last):
  File "/scratch/eo41/dino/train_dino.py", line 443, in <module>
    train_dino(args)
  File "/scratch/eo41/dino/train_dino.py", line 242, in train_dino
    train_stats = train_one_epoch(student, teacher, teacher_without_ddp, dino_loss, data_loader, optimizer, lr_schedule, wd_schedule, momentum_schedule, epoch, fp16_scaler, args)
  File "/scratch/eo41/dino/train_dino.py", line 258, in train_one_epoch
    param_group["lr"] = lr_schedule[GLOBAL_ITER]
IndexError: index 100000 is out of bounds for axis 0 with size 100000
Traceback (most recent call last):
  File "/scratch/eo41/dino/train_dino.py", line 443, in <module>
    train_dino(args)
  File "/scratch/eo41/dino/train_dino.py", line 242, in train_dino
    train_stats = train_one_epoch(student, teacher, teacher_without_ddp, dino_loss, data_loader, optimizer, lr_schedule, wd_schedule, momentum_schedule, epoch, fp16_scaler, args)
  File "/scratch/eo41/dino/train_dino.py", line 258, in train_one_epoch
    param_group["lr"] = lr_schedule[GLOBAL_ITER]
IndexError: index 100000 is out of bounds for axis 0 with size 100000
srun: error: ga007: task 2: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=23495044.0
slurmstepd: error: *** STEP 23495044.0 ON ga007 CANCELLED AT 2022-08-13T11:09:23 ***
srun: error: ga007: task 0: Exited with exit code 1
srun: error: ga007: tasks 1,3: Terminated
srun: Force Terminated StepId=23495044.0
Done
